import type { AppId, Edition, GameTitle, HardwareDevice, Pkg } from "./types";
import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Box,
  Clapperboard,
  Code2,
  Compass,
  Cpu,
  EyeOff,
  Folder,
  Gamepad2,
  Hexagon,
  LayoutDashboard,
  LayoutGrid,
  PenLine,
  RotateCcw,
  Shield,
  SlidersHorizontal,
  SquareTerminal,
  Wifi,
  Workflow,
} from "lucide-react";

export const EDITIONS: { id: Edition; name: string; blurb: string }[] = [
  { id: "home", name: "Home", blurb: "Simple, calm, ready for everyday work." },
  { id: "pro", name: "Pro", blurb: "Creators and professionals." },
  { id: "developer", name: "Developer", blurb: "Toolchains, terminals, sandboxes." },
  { id: "gaming", name: "Gaming", blurb: "GameCore, overlays, low latency." },
  { id: "server", name: "Server", blurb: "Headless-first, services, isolation." },
  { id: "enterprise", name: "Enterprise", blurb: "Policy, recovery, fleet-ready." },
  { id: "security", name: "Security Lab", blurb: "Authorized defensive research." },
];

export const APP_META: Record<
  AppId,
  { name: string; blurb: string; icon: LucideIcon; category: string }
> = {
  files: { name: "AI Files", blurb: "Universal file manager", icon: Folder, category: "System" },
  terminal: {
    name: "AI Terminal",
    blurb: "Helix shell with AIA",
    icon: SquareTerminal,
    category: "System",
  },
  browser: { name: "AI Browser", blurb: "Helix net", icon: Compass, category: "Internet" },
  settings: {
    name: "AI Settings",
    blurb: "One place for the machine",
    icon: SlidersHorizontal,
    category: "System",
  },
  monitor: {
    name: "System Monitor",
    blurb: "Live process and resource view",
    icon: Activity,
    category: "System",
  },
  hardware: {
    name: "Hardware Center",
    blurb: "Devices, thermals, firmware",
    icon: Cpu,
    category: "System",
  },
  devspace: {
    name: "AI DevSpace",
    blurb: "Isolated project environments",
    icon: Code2,
    category: "Create",
  },
  gamehub: {
    name: "AI GameHub",
    blurb: "GameCore library and profiles",
    icon: Gamepad2,
    category: "Play",
  },
  notes: { name: "AI Notes", blurb: "Fast local notes", icon: PenLine, category: "Create" },
  media: {
    name: "Media Studio",
    blurb: "Play, cut, color",
    icon: Clapperboard,
    category: "Create",
  },
  security: {
    name: "Security Center",
    blurb: "Sandbox, firewall, integrity",
    icon: Shield,
    category: "Protect",
  },
  recovery: {
    name: "AI Recovery",
    blurb: "Snapshots and rollback",
    icon: RotateCcw,
    category: "Protect",
  },
  packages: {
    name: "Package Center",
    blurb: "AIPM signed software",
    icon: Box,
    category: "System",
  },
  workspaces: {
    name: "Workspace Manager",
    blurb: "Project rooms",
    icon: LayoutGrid,
    category: "Create",
  },
  privacy: {
    name: "Privacy Center",
    blurb: "What leaves this machine",
    icon: EyeOff,
    category: "Protect",
  },
  control: {
    name: "Control Center",
    blurb: "System at a glance",
    icon: LayoutDashboard,
    category: "System",
  },
  flow: { name: "AI Flow", blurb: "Natural-language automation", icon: Workflow, category: "Create" },
  atlas: { name: "AI OS Atlas", blurb: "Architecture of Helix", icon: Hexagon, category: "System" },
  network: { name: "Network", blurb: "Links, VPN, discovery", icon: Wifi, category: "Internet" },
};

export const FEATURED_BY_EDITION: Record<Edition, AppId[]> = {
  home: ["files", "browser", "notes", "media", "settings", "packages"],
  pro: ["files", "media", "notes", "packages", "flow", "settings"],
  developer: ["terminal", "devspace", "files", "packages", "workspaces", "atlas"],
  gaming: ["gamehub", "monitor", "hardware", "packages", "settings", "media"],
  server: ["terminal", "monitor", "network", "security", "packages", "recovery"],
  enterprise: ["security", "privacy", "recovery", "control", "network", "settings"],
  security: ["security", "privacy", "terminal", "network", "recovery", "atlas"],
};

export const PACKAGES: Pkg[] = [
  {
    id: "blender",
    name: "Blender",
    version: "4.4.1",
    category: "Create",
    description: "3D creation suite via AIX Linux compatibility.",
    size: "412 MB",
    signed: true,
    installed: false,
    runtime: "linux",
  },
  {
    id: "helix-code",
    name: "Helix Code",
    version: "1.96.0",
    category: "Develop",
    description: "VS Code compatible editor with AIA inline.",
    size: "128 MB",
    signed: true,
    installed: true,
    runtime: "native",
  },
  {
    id: "godot",
    name: "Godot",
    version: "4.4",
    category: "Play",
    description: "Open game engine, GameCore accelerated.",
    size: "86 MB",
    signed: true,
    installed: false,
    runtime: "native",
  },
  {
    id: "node",
    name: "Node.js",
    version: "22.14.0",
    category: "Develop",
    description: "JavaScript runtime for DevSpace.",
    size: "48 MB",
    signed: true,
    installed: true,
    runtime: "native",
  },
  {
    id: "rustc",
    name: "Rust Toolchain",
    version: "1.86.0",
    category: "Develop",
    description: "rustc, cargo, clippy, rust-analyzer.",
    size: "214 MB",
    signed: true,
    installed: false,
    runtime: "native",
  },
  {
    id: "python",
    name: "Python",
    version: "3.13.2",
    category: "Develop",
    description: "CPython with venv isolation.",
    size: "62 MB",
    signed: true,
    installed: true,
    runtime: "native",
  },
  {
    id: "docker",
    name: "Containers",
    version: "27.5",
    category: "Develop",
    description: "Native container runtime (not a dockerd fork).",
    size: "94 MB",
    signed: true,
    installed: true,
    runtime: "native",
  },
  {
    id: "k3",
    name: "Helix Cluster",
    version: "1.32",
    category: "Develop",
    description: "Lightweight Kubernetes-compatible control plane.",
    size: "78 MB",
    signed: true,
    installed: false,
    runtime: "native",
  },
  {
    id: "ffmpeg",
    name: "FFmpeg",
    version: "7.1",
    category: "Create",
    description: "Media encode and inspect tools.",
    size: "38 MB",
    signed: true,
    installed: true,
    runtime: "native",
  },
  {
    id: "obs",
    name: "Capture Studio",
    version: "31.0",
    category: "Create",
    description: "Screen recording and streaming.",
    size: "156 MB",
    signed: true,
    installed: false,
    runtime: "linux",
  },
  {
    id: "proton",
    name: "GameCore Proton",
    version: "10.0",
    category: "Play",
    description: "DirectX-to-Vulkan translation for GameCore.",
    size: "502 MB",
    signed: true,
    installed: true,
    runtime: "native",
  },
  {
    id: "libre",
    name: "Helix Office",
    version: "25.2",
    category: "Work",
    description: "Documents, sheets, decks — native.",
    size: "288 MB",
    signed: true,
    installed: false,
    runtime: "native",
  },
  {
    id: "gimp",
    name: "Pixel Forge",
    version: "3.0",
    category: "Create",
    description: "Raster studio via AIX.",
    size: "118 MB",
    signed: true,
    installed: false,
    runtime: "linux",
  },
  {
    id: "go",
    name: "Go",
    version: "1.24.1",
    category: "Develop",
    description: "Go compiler and modules.",
    size: "74 MB",
    signed: true,
    installed: false,
    runtime: "native",
  },
  {
    id: "jdk",
    name: "Java JDK",
    version: "23",
    category: "Develop",
    description: "OpenJDK with Helix filesystem layout.",
    size: "198 MB",
    signed: true,
    installed: false,
    runtime: "native",
  },
  {
    id: "dotnet",
    name: ".NET SDK",
    version: "9.0",
    category: "Develop",
    description: "C# and .NET for DevSpace.",
    size: "266 MB",
    signed: true,
    installed: false,
    runtime: "native",
  },
  {
    id: "clang",
    name: "LLVM / Clang",
    version: "20.1",
    category: "Develop",
    description: "C/C++ toolchain alongside GCC.",
    size: "312 MB",
    signed: true,
    installed: true,
    runtime: "native",
  },
  {
    id: "gcc",
    name: "GCC",
    version: "14.2",
    category: "Develop",
    description: "GNU compiler collection, Helix sysroot.",
    size: "244 MB",
    signed: true,
    installed: true,
    runtime: "native",
  },
];

export const GAMES: GameTitle[] = [
  {
    id: "prism-drift",
    name: "Prism Drift",
    studio: "Helix Labs",
    runtime: "native",
    fpsCap: 144,
    installed: true,
  },
  {
    id: "north-rail",
    name: "North Rail",
    studio: "Quiet Signal",
    runtime: "gamecore",
    fpsCap: 120,
    installed: true,
  },
  {
    id: "ash-protocol",
    name: "Ash Protocol",
    studio: "Third Orbit",
    runtime: "gamecore",
    fpsCap: 60,
    installed: false,
  },
  {
    id: "tidal-form",
    name: "Tidal Form",
    studio: "Clearwater",
    runtime: "native",
    fpsCap: 240,
    installed: false,
  },
];

export const HARDWARE: HardwareDevice[] = [
  {
    id: "cpu",
    name: "Helix CPU — 16c / 32t",
    kind: "cpu",
    status: "ok",
    detail: "Hybrid big.LITTLE, 5.4 GHz boost",
    temp: 48,
    usage: 18,
    power: 42,
    driver: "helix-cpu 6.2",
    firmware: "uCode 2026.09",
  },
  {
    id: "gpu",
    name: "Helix GPU — 16 GB",
    kind: "gpu",
    status: "ok",
    detail: "Vulkan 1.3, GameCore DX12",
    temp: 52,
    usage: 8,
    power: 38,
    driver: "helix-gpu 26.3",
    firmware: "VBIOS 1.42",
  },
  {
    id: "ram",
    name: "32 GB LPDDR5X",
    kind: "ram",
    status: "ok",
    detail: "Dual channel, 7500 MT/s",
    usage: 34,
    power: 6,
    driver: "helix-mm 6.2",
    firmware: "SPD",
  },
  {
    id: "nvme",
    name: "1 TB NVMe",
    kind: "storage",
    status: "ok",
    detail: "Btrfs + Helix snapshots",
    usage: 41,
    temp: 39,
    power: 4,
    driver: "nvme 2.1",
    firmware: "2.4.1",
  },
  {
    id: "wifi",
    name: "Wi-Fi 7",
    kind: "wifi",
    status: "ok",
    detail: "Connected — HelixNet 6 GHz",
    driver: "helix-wifi 4.1",
    firmware: "FW 88.12",
  },
  {
    id: "eth",
    name: "2.5 GbE",
    kind: "ethernet",
    status: "offline",
    detail: "Cable unplugged",
    driver: "helix-nic 3.8",
    firmware: "1.09",
  },
  {
    id: "bt",
    name: "Bluetooth 5.4",
    kind: "bluetooth",
    status: "ok",
    detail: "Idle",
    driver: "helix-bt 5.4",
    firmware: "22.1",
  },
  {
    id: "audio",
    name: "Helix Audio",
    kind: "audio",
    status: "ok",
    detail: "Speakers + HDMI",
    driver: "pipe-helix 1.2",
    firmware: "DSP 9",
  },
  {
    id: "display",
    name: "Built-in 15.2\" OLED",
    kind: "display",
    status: "ok",
    detail: "2880×1800 @ 120 Hz",
    driver: "helix-kms 6.2",
    firmware: "TCON 4.2",
  },
  {
    id: "kb",
    name: "Keyboard + Pointer",
    kind: "input",
    status: "ok",
    detail: "HID composite",
    driver: "helix-hid 1.6",
    firmware: "1.0",
  },
  {
    id: "cam",
    name: "Studio Camera",
    kind: "camera",
    status: "ok",
    detail: "1080p, privacy shutter closed",
    driver: "uvc 1.5",
    firmware: "2.11",
  },
];

export const SETTINGS_INDEX: { keys: string; id: string; title: string; group: string }[] = [
  { keys: "gpu performance game mode overlay fps", id: "gaming", title: "Gaming", group: "Gaming" },
  { keys: "theme dark light wallpaper appearance", id: "display", title: "Display", group: "Display" },
  { keys: "wifi ethernet vpn dns firewall network", id: "network", title: "Network", group: "Network" },
  { keys: "microphone camera location telemetry privacy", id: "privacy", title: "Privacy", group: "Privacy" },
  { keys: "users accounts guest child admin", id: "users", title: "Users", group: "Users" },
  { keys: "updates rollback snapshot recovery", id: "updates", title: "Updates", group: "Updates" },
  { keys: "power battery thermals performance mode", id: "power", title: "Power", group: "Power" },
  { keys: "ai aia assistant on-device models", id: "ai", title: "AI", group: "AI" },
  { keys: "developer terminal sdk toolchain", id: "developer", title: "Developer", group: "Developer" },
  { keys: "sound volume output input", id: "sound", title: "Sound", group: "Sound" },
  { keys: "storage disk encryption snapshots", id: "storage", title: "Storage", group: "Storage" },
  { keys: "security sandbox firewall encryption", id: "security", title: "Security", group: "Security" },
  { keys: "accessibility contrast reader magnifier", id: "access", title: "Accessibility", group: "Accessibility" },
  { keys: "virtualization vm container sandbox", id: "virt", title: "Virtualization", group: "Virtualization" },
  { keys: "bluetooth devices pair", id: "bluetooth", title: "Bluetooth", group: "Bluetooth" },
  { keys: "backup cloud sync", id: "backup", title: "Backup", group: "Backup" },
];

export function uid(prefix = "id") {
  return `${prefix}-${Math.random().toString(36).slice(2, 9)}`;
}
